#!/usr/bin/env bash
# stamp-version.sh — auto-stamp app version with today's UTC.
#
# Invoked by the "Stamp Version" Run Script build phase in each app
# target. Writes config/version-generated.xcconfig (gitignored) so the
# next xcconfig resolution + Xcode's General tab see today's stamp, and
# patches the just-processed Info.plist in place so the CURRENT build
# bundle gets it too (build settings were already resolved before this
# phase ran, so the in-bundle plist would otherwise still have yesterday's
# stamp).

set -euo pipefail

MARKETING="$(date -u +%y.%m.%d)"
BUILD="$(date -u +%y%m%d.%H%M)"

OUT="${SRCROOT}/config/version-generated.xcconfig"
cat > "$OUT" <<EOF
// AUTO-GENERATED by Scripts/stamp-version.sh. Do not edit; do not commit.
// Overrides config/version.xcconfig via Base.xcconfig's optional include.
MARKETING_VERSION       = ${MARKETING}
CURRENT_PROJECT_VERSION = ${BUILD}
EOF

INFO="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
if [[ -f "$INFO" ]]; then
    /usr/libexec/PlistBuddy \
        -c "Set :CFBundleShortVersionString ${MARKETING}" \
        -c "Set :CFBundleVersion ${BUILD}" \
        "$INFO"
fi

echo "stamped ${MARKETING} / ${BUILD}"
